---

- name: create registrator container
  docker_container:
    name: "{{registrator_name}}"
    image: "{{consul_container_image}}"
    network_mode: bridge
    restart_policy: always
    volumes:
       - "{{registrator_docker_socket}}:/tmp/docker.sock:ro"
    command: "{{registrator_endpoint}}"
