# This is for testing purposes only
# See https://github.com/hyperledger/fabric/blob/master/docs/Setup/Network-setup.md for more details.
version: "2"

services:
  vp:
    image: gbolo/hyperledger-peer:pbft-master
    restart: unless-stopped
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=info  # critical, error, warning, notice, info, debug
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
      - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=10s
      #- CORE_VM_ENDPOINT=http://172.17.0.1:2375
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hyperledger_overlay1
    expose:
      - "30303"
      - "30304"
      - "31315"
    volumes: # use if docker.sock is mapped to CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    command: peer node start
    networks:
      - overlay1
