---

consul_container_volume: /opt/dkr_consul
consul_container_config_volume: "{{consul_container_volume}}/config"
consul_container_data_volume: "{{consul_container_volume}}/data"
consul_container_state: started
consul_container_image: "consul"
consul_container_network: "host"

## Configuration
consul_config_node_name: "{{ansible_hostname}}"
consul_config_is_server: false
consul_config_server_bootstrap: "false"
consul_config_server_ip: "10.0.0.1"
consul_config_leave_on_terminate: "true"
consul_config_datacenter: "LAB1"
consul_config_domain: "midgar.local"
consul_config_recursor: "8.8.8.8"
consul_config_bind_addr: "{{ansible_default_ipv4.address}}"
consul_config_dns_port: 8600
consul_config_advertise_addr: "{{ansible_default_ipv4.address}}"

## Volume Permissions
consul_container_volume_owner: root
consul_container_volume_group: root
consul_container_volume_mode: 0777
