---

- name: create docker volume mount
  file: path={{pdns_container_volume}} state=directory mode=0755

- name: add pdns.conf
  template: src=pdns.conf.j2 dest={{pdns_container_volume}}/pdns.conf mode=0755
  register: pdns_config
