---

- name: create pdns container
  docker_container:
    name: powerdns
    image: gbolo/powerdns
    state: started
    restart_policy: always
    volumes:
     - "{{pdns_container_volume}}/pdns.conf:/usr/local/etc/pdns.conf:ro"
    ports:
     - "53:53"
     - "53:53/udp"
     - "{{pdns_api_port_expose}}:{{pdns_api_port}}"
