---

- name: create pdns container
  docker_container:
    name: powerdns
    image: "{{pdns_container_image}}"
    state: "{{pdns_container_state}}"
    restart: "{{pdns_config.changed}}"
    # disable restart_policy due to this bug: #3864
    #restart_policy: always
    volumes:
      - "{{pdns_container_volume}}/pdns.conf:/usr/local/etc/pdns.conf:ro"
    exposed_ports:
      # expose ports not in Dockerfile
      - "{{pdns_api_port}}"
    ports:
      - "53:53"
      - "53:53/udp"
      - "{{pdns_api_port_expose}}:{{pdns_api_port}}"
