---

- name: Install Required Packages
  yum: name={{item}} state={{docker_pkg_state}} disable_gpg_check=no
  with_items:
    - python-docker-py

- name: create docker volume mount
  file: path=/opt/dkr-powerdns state=directory mode=0755

- name: create pdns container
  docker_container:
    name: powerdns
    image: gbolo/powerdns
    state: started
    restart_policy: always
    volumes:
     - "/opt/dkr-powerdns/pdns.conf:/usr/local/etc/pdns.conf:ro"
    ports:
     - "53:53"
     - "53:53/udp"
     - "8081:8081"

- name: add pdns.conf
  template: src=pdns.conf.j2 dest=/opt/dkr-powerdns/pdns.conf mode=0755
  notify: restart dkr-pdns
