---

swarm_manager_port: 4000
swarm_manager_name: swarm_manager
swarm_manager_ip: "0.0.0.0"
swarm_is_manager: false
swarm_node_name: swarm_node
swarm_image: swarm
swarm_consul_ip: "10.0.0.10"
swarm_consul_port: "{{consul_config_port}}"
swarm_consul_path: swarm
swarm_bind_addr_ip_filter: "10.0.0.0/24"
