---

swarm_manager_port: 4000
swarm_manager_name: swarm_manager
swarm_manager_ip: "0.0.0.0"
swarm_is_manager: false
swarm_is_node: true
swarm_node_name: swarm_node
swarm_image: swarm
swarm_consul_ip: "10.0.0.10"
swarm_consul_port: 8500
swarm_consul_path: swarm
swarm_bind_addr_ip_filter: "10.0.0.0/24"
swarm_node_ip: "{{ansible_default_ipv4.address}}"
docker_api_port: 2375

# sending list as docker command to support swarm entrypoint
swarm_manager_cmd:
  - "manage"
  - "-H"
  - ":{{swarm_manager_port}}"
  - "--advertise"
  - "{{swarm_manager_ip}}:{{swarm_manager_port}}"
  - "consul://{{swarm_consul_ip}}:{{swarm_consul_port}}/{{swarm_consul_path}}"

swarm_node_cmd:
  - "join"
  - "--addr={{swarm_node_ip}}:{{docker_api_port}}"
  - "consul://{{swarm_consul_ip}}:{{swarm_consul_port}}/{{swarm_consul_path}}"
