---
- name: restart hyperledger peer
  service: name=hl-peer state=restarted

- name: reload systemd
  # systemd module not available before ansible version 2.2
  #systemd: daemon_reload=yes name=docker
  # work around - use command
  command: systemctl daemon-reload
