---

- name: Install Tools
  yum: name={{item}} state=present disable_gpg_check=no
  with_items:
    - MySQL-python

- name: Install MYSQL
  yum: name=mariadb-server state=present disable_gpg_check=no

- name: Ensure MYSQL Runing and Enabled
  service: name=mariadb state=started enabled=yes

- name: create demo database
  mysql_db: name={{ db_name }} state=present

- name: create database user
  mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL
              host='{{ db_user_host }}' state=present

# Copy Database file for import
- name: copyig database sql file
  copy: src={{db_import_file}} dest=/tmp
  when: db_import_enable

# Imports file.sql similiar to mysql -u <username> -p <password> < hostname.sql
- name: Import Database Structure
  mysql_db: state=import name={{db_name}} target=/tmp/{{db_import_file}}
  when: db_import_enable
