---

- name: create pdns container
  docker_container:
    name: powerdns_admin
    image: "{{pdnsgui_container_image}}"
    state: "{{pdnsgui_container_state}}"
    restart: "{{pdnsgui_config.changed}}"
    # disable restart_policy due to this bug: #3864
    #restart_policy: always
    volumes:
      - "{{pdnsgui_container_volume}}/config.py:/opt/PowerDNS-Admin/config.py:ro"
    exposed_ports:
      # expose ports not in Dockerfile
      - "{{pdnsgui_exposed_port}}"
    ports:
      - "{{pdnsgui_published_port}}:{{pdnsgui_exposed_port}}"
