---

- name: create pdns container
  docker_container:
    name: powerdns_admin
    image: "{{pdnsgui_container_image}}"
    state: "{{pdnsgui_container_state}}"
    restart: "{{pdnsgui_config.changed}}"
    restart_policy: always
    volumes:
      - "{{pdns_container_volume}}/config.py:/opt/PowerDNS-Admin/config.py:ro"
    exposed_ports:
      # expose ports not in Dockerfile
      - "{{pdnsgui_exposed_port}}"
    ports:
      - "{{pdnsgui_published_port}}:{{pdnsgui_exposed_port}}"
