---
# EPEL Repo
- name: Install EPEL YUM Repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes

# Install common packages
- name: Install Common Packages
  yum: name={{item}} state={{docker_pkg_state}} disable_gpg_check=no
  with_items:
    - vim
    - tree
    - net-tools
    - tcpdump
    - nmap

# Install VMware tools when needed
- name: Installing VMware Tools
  yum: name=open-vm-tools state=present disable_gpg_check=no
  when: ansible_virtualization_type == "VMware"
