---

- name: Install Required Packages
  yum: name={{item}} state={{docker_pkg_state}} disable_gpg_check=no
  with_items:
    - docker-engine

- name: copy docker-compose binary
  copy: src=docker-compose_1.7.1 dest=/usr/local/bin/docker-compose mode=0755
  when: enable_docker_compose
