---

# delete consul data
- block:

  - name: stop consul container
    command: docker stop consul
    ignore_errors: yes

  - name: delete consul data
    file: path={{consul_container_data_volume}} state=absent
    notify: restart consul container

  when: consul_delete_data

# other tasks
- name: create docker volume mount
  file: path={{consul_container_volume}} state=directory mode=0755

- name: create docker config volume mount
  file: path={{consul_container_config_volume}} state=directory
        owner={{consul_container_volume_owner}}
        group={{consul_container_volume_group}}
        mode={{consul_container_volume_mode}}

- name: create docker data volume mount
  file: path={{consul_container_data_volume}} state=directory
        owner={{consul_container_volume_owner}}
        group={{consul_container_volume_group}}
        mode={{consul_container_volume_mode}}

- name: Copy main consul config
  template: src=consul.json.j2
            dest={{consul_container_config_volume}}/consul.json
            owner=root group=root mode=644

- name: Copy dnsmasq config
  template: src=dnsmasq_consul.j2
            dest=/etc/dnsmasq.d/10_consul
            owner=root group=root mode=644
