---

- name: create docker volume mount
  file: path={{consul_container_volume}} state=directory mode=0755

- name: create docker config volume mount
  file: path={{consul_container_config_volume}} state=directory mode=0755

- name: create docker data volume mount
  file: path={{consul_container_data_volume}} state=directory mode=0775

- name: Copy main consul config
  template: src=consul.json.j2
            dest={{consul_container_config_volume}}/consul.json
            owner=root group=root mode=644
