---

- name: create consul container
  docker_container:
    name: consul
    image: "{{consul_container_image}}"
    network_mode: bridge
    restart_policy: always
    volumes:
       - "{{consul_container_config_volume}}:/consul/config"
       - "{{consul_container_data_volume}}:/consul/data"
    published_ports:
       - "8300:8300"
       - "8301:8301"
       - "8301:8301/udp"
       - "8302:8302"
       - "8302:8302/udp"
       - "8400:8400"
       - "8500:8500"
    command: "agent"
