---

- name: create swarm manager container
  docker_container:
    name: "{{swarm_manager_name}}"
    image: "{{swarm_image}}"
    state: started
    published_ports:
       - "{{swarm_manager_port}}:{{swarm_manager_port}}"
    command: "manage -H :{{swarm_manager_port}} --advertise {{swarm_manager_ip}}:{{swarm_manager_port}} consul://{{swarm_consul_ip}}:{{swarm_consul_port}}/{{swarm_consul_path}}"
  when: swarm_is_manager


- name: create swarm node container
  docker_container:
    name: "{{swarm_node_name}}"
    image: "{{swarm_image}}"
    state: started
    command: "join --advertise '{{ ansible_all_ipv4_addresses | ipaddr(swarm_bind_addr_ip_filter) | random }}':2375 consul://{{swarm_consul_ip}}:{{swarm_consul_port}}/{{swarm_consul_path}}"
  when: not swarm_is_manager
