---

- name: create swarm manager container
  docker_container:
    name: "{{swarm_manager_name}}"
    image: "{{swarm_image}}"
    state: started
    restart_policy: always
    # expose ports not in Dockerfile
    exposed_ports:
      - "{{swarm_manager_port}}"
    ports:
      - "{{swarm_manager_port}}:{{swarm_manager_port}}"
    command: "{{swarm_manager_cmd}}"
  when: swarm_is_manager

- name: create swarm node container
  docker_container:
    name: "{{swarm_node_name}}"
    image: "{{swarm_image}}"
    state: started
    restart_policy: always
    command: "{{swarm_node_cmd}}"
# when: not swarm_is_manager
  when: swarm_is_node
