# InfluxDB Repo
- name: Install influxdb YUM Repo
  yum_repository:
    name: "influxdb"
    description: InfluxDB Repository - CentOS
    baseurl: "https://repos.influxdata.com/centos/$releasever/$basearch/stable"
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes
